/*
SQLyog Community v13.1.5  (64 bit)
MySQL - 5.7.23 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `scormvars_full_data` (
	`id` int (11),
	`type` varchar (150),
	`params_key` varchar (150),
	`value` text ,
	`timestamp` varchar (300),
	`activity_id` varchar (3000),
	`event` varchar (3000)
); 
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('985','GetValue','cmi.launch_data','','9/9/2019, 7:06:41 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on launch');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('986','GetValue','cmi.core.entry','ab-initio','9/9/2019, 7:06:44 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on launch');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('987','GetValue','cmi.core.lesson_location','','9/9/2019, 7:06:48 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on launch');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('988','GetValue','cmi.student_preference.language','','9/9/2019, 7:06:50 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on launch');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('989','GetValue','cmi.student_preference.audio','','9/9/2019, 7:06:52 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on launch');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('990','GetValue','cmi.student_preference.speed','','9/9/2019, 7:06:54 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on launch');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('991','GetValue','cmi.student_preference.text','','9/9/2019, 7:06:56 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on launch');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('992','GetValue','cmi.core.credit','credit','9/9/2019, 7:06:58 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on launch');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('993','GetValue','cmi.core.lesson_mode','','9/9/2019, 7:07:00 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on launch');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('994','GetValue','cmi.suspend_data','','9/9/2019, 7:07:02 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on launch');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('995','GetValue','cmi.core.total_time','0000:00:00','9/9/2019, 7:07:04 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on launch');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('996','GetValue','cmi.core.student_id','007','9/9/2019, 7:07:07 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on launch');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('997','Statement','Statement','\"{\\\"actor\\\":{\\\"mbox\\\":\\\"mailto:deepak@nextsoftwaresolutions.com\\\",\\\"name\\\":\\\"nsstester\\\",\\\"objectType\\\":\\\"Agent\\\"},\\\"verb\\\":{\\\"id\\\":\\\"http://adlnet.gov/expapi/verbs/attempted\\\",\\\"display\\\":{\\\"de-DE\\\":\\\"versuchte\\\",\\\"en-US\\\":\\\"attempted\\\",\\\"fr-FR\\\":\\\"a essayé\\\",\\\"es-ES\\\":\\\"intentó\\\",\\\"ar-AR\\\":\\\"حاول\\\"}},\\\"object\\\":{\\\"id\\\":\\\"http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic\\\",\\\"definition\\\":{\\\"type\\\":\\\"http://adlnet.gov/expapi/activities/lesson\\\"}},\\\"context\\\":{\\\"contextActivities\\\":{\\\"grouping\\\":[{\\\"id\\\":\\\"http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic?attemptId=0f7ff49e-aaae-4339-a5b5-be41b1a815ac\\\",\\\"objectType\\\":\\\"Activity\\\",\\\"definition\\\":{\\\"type\\\":\\\"http://adlnet.gov/expapi/activities/attempt\\\"}},{\\\"id\\\":\\\"\\\",\\\"objectType\\\":\\\"Activity\\\",\\\"definition\\\":{\\\"type\\\":\\\"http://adlnet.gov/expapi/activities/course\\\"}},\\\"\\\"],\\\"category\\\":[{\\\"id\\\":\\\"https://w3id.org/xapi/scorm\\\"}]},\\\"registration\\\":\\\"71b6f8ce-e63b-475e-a8c1-62544759cbb4\\\"},\\\"id\\\":\\\"38d335a7-4f6d-480c-8db6-018232c5b191\\\"}\"','9/9/2019, 7:07:09 PM','','on launch');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('998','GetValue','cmi.core.total_time','0000:00:00','9/9/2019, 7:07:14 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on launch');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('999','SetValue','cmi.core.lesson_location','index.html','9/9/2019, 7:07:16 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on launch');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('1000','SetValue','cmi.core.lesson_status','incomplete','9/9/2019, 7:07:18 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on launch');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('1001','SetValue','cmi.interactions.0.id','Q1','9/9/2019, 7:07:20 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on launch');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('1002','SetValue','cmi.interactions.1.id','A1','9/9/2019, 7:07:22 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on launch');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('1003','SetValue','cmi.interactions.0.type','matching','9/9/2019, 7:08:46 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on clicking check answers');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('1004','SetValue','cmi.interactions.0.student_response','Q1: b ,c ,a ','9/9/2019, 7:08:48 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on clicking check answers');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('1005','Statement','Statement','\"{\\\"actor\\\":{\\\"mbox\\\":\\\"mailto:deepak@nextsoftwaresolutions.com\\\",\\\"name\\\":\\\"nsstester\\\",\\\"objectType\\\":\\\"Agent\\\"},\\\"verb\\\":{\\\"id\\\":\\\"http://adlnet.gov/expapi/verbs/answered\\\",\\\"display\\\":{\\\"de-DE\\\":\\\"beantwortete\\\",\\\"en-US\\\":\\\"answered\\\",\\\"fr-FR\\\":\\\"a répondu\\\",\\\"es-ES\\\":\\\"contestó\\\",\\\"ar-AR\\\":\\\"أجاب\\\"}},\\\"object\\\":{\\\"objectType\\\":\\\"Activity\\\",\\\"id\\\":\\\"http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic/interactions/Q1\\\",\\\"definition\\\":{\\\"type\\\":\\\"http://adlnet.gov/expapi/activities/cmi.interaction\\\",\\\"interactionType\\\":\\\"matching\\\",\\\"correctResponsesPattern\\\":[],\\\"source\\\":[],\\\"target\\\":[]}},\\\"context\\\":{\\\"contextActivities\\\":{\\\"parent\\\":[{\\\"id\\\":\\\"http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic\\\",\\\"objectType\\\":\\\"Activity\\\",\\\"definition\\\":{\\\"type\\\":\\\"http://adlnet.gov/expapi/activities/lesson\\\"}}],\\\"grouping\\\":[{\\\"id\\\":\\\"http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic?attemptId=0f7ff49e-aaae-4339-a5b5-be41b1a815ac\\\",\\\"objectType\\\":\\\"Activity\\\",\\\"definition\\\":{\\\"type\\\":\\\"http://adlnet.gov/expapi/activities/attempt\\\"}},{\\\"id\\\":\\\"\\\",\\\"objectType\\\":\\\"Activity\\\",\\\"definition\\\":{\\\"type\\\":\\\"http://adlnet.gov/expapi/activities/course\\\"}},\\\"\\\"],\\\"category\\\":[{\\\"id\\\":\\\"https://w3id.org/xapi/scorm\\\"}]},\\\"registration\\\":\\\"71b6f8ce-e63b-475e-a8c1-62544759cbb4\\\"},\\\"result\\\":{\\\"response\\\":\\\"Q1: b ,c ,a \\\"},\\\"id\\\":\\\"41b844ff-66c1-4b24-8f13-d4e339dcfc63\\\"}\"','9/9/2019, 7:08:50 PM','','on clicking check answers');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('1006','SetValue','cmi.core.score.min','0','9/9/2019, 7:08:52 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on clicking check answers');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('1007','SetValue','cmi.core.score.max','10','9/9/2019, 7:08:54 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on clicking check answers');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('1008','SetValue','cmi.core.score.raw','5','9/9/2019, 7:08:57 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on clicking check answers');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('1009','Statement','Statement','\"{\\\"actor\\\":{\\\"mbox\\\":\\\"mailto:deepak@nextsoftwaresolutions.com\\\",\\\"name\\\":\\\"nsstester\\\",\\\"objectType\\\":\\\"Agent\\\"},\\\"verb\\\":{\\\"id\\\":\\\"http://adlnet.gov/expapi/verbs/scored\\\",\\\"display\\\":{\\\"de-DE\\\":\\\"erreichte\\\",\\\"en-US\\\":\\\"scored\\\",\\\"fr-FR\\\":\\\"a marqué\\\",\\\"es-ES\\\":\\\"anotó\\\",\\\"ar-AR\\\":\\\"سحل النقاط\\\"}},\\\"object\\\":{\\\"id\\\":\\\"http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic\\\",\\\"definition\\\":{\\\"type\\\":\\\"http://adlnet.gov/expapi/activities/lesson\\\"}},\\\"context\\\":{\\\"contextActivities\\\":{\\\"grouping\\\":[{\\\"id\\\":\\\"http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic?attemptId=0f7ff49e-aaae-4339-a5b5-be41b1a815ac\\\",\\\"objectType\\\":\\\"Activity\\\",\\\"definition\\\":{\\\"type\\\":\\\"http://adlnet.gov/expapi/activities/attempt\\\"}},{\\\"id\\\":\\\"\\\",\\\"objectType\\\":\\\"Activity\\\",\\\"definition\\\":{\\\"type\\\":\\\"http://adlnet.gov/expapi/activities/course\\\"}},\\\"\\\"],\\\"category\\\":[{\\\"id\\\":\\\"https://w3id.org/xapi/scorm\\\"}]},\\\"registration\\\":\\\"71b6f8ce-e63b-475e-a8c1-62544759cbb4\\\"},\\\"result\\\":{\\\"score\\\":{\\\"scaled\\\":0.05}},\\\"id\\\":\\\"f99bda73-c851-4fbf-a007-db9ebce319ec\\\"}\"','9/9/2019, 7:08:59 PM','','on clicking check answers');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('1010','SetValue','cmi.core.lesson_status','incomplete','9/9/2019, 7:09:01 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on clicking check answers');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('1011','SetValue','cmi.interactions.0.result','correct','9/9/2019, 7:09:03 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on clicking check answers');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('1012','SetValue','cmi.interactions.0.correct_responses.0.pattern','1','9/9/2019, 7:09:05 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on clicking check answers');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('1013','SetValue','cmi.interactions.0.correct_responses.1.pattern','2','9/9/2019, 7:09:07 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on clicking check answers');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('1014','SetValue','cmi.interactions.0.correct_responses.2.pattern','0','9/9/2019, 7:09:09 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on clicking check answers');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('1015','SetValue','cmi.core.session_time','00:03:03.66','9/9/2019, 7:10:28 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on clicking finish button');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('1016','SetValue','cmi.core.lesson_location','index.html','9/9/2019, 7:10:30 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on clicking finish button');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('1017','SetValue','cmi.core.lesson_status','incomplete','9/9/2019, 7:10:32 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on clicking finish button');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('1018','GetValue','cmi.core.lesson_status','incomplete','9/9/2019, 7:10:40 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on clicking finish button');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('1019','GetValue','cmi.core.lesson_status','incomplete','9/9/2019, 7:10:42 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on clicking finish button');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('1020','GetValue','cmi.core.score.raw','5','9/9/2019, 7:10:44 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on clicking finish button');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('1021','GetValue','cmi.core.score.raw','5','9/9/2019, 7:10:46 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on clicking finish button');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('1022','GetValue','cmi.core.score.min','0','9/9/2019, 7:10:48 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on clicking finish button');
insert into `scormvars_full_data` (`id`, `type`, `params_key`, `value`, `timestamp`, `activity_id`, `event`) values('1023','GetValue','cmi.core.score.max','10','9/9/2019, 7:10:50 PM','http://nss-grassblade.com/wordpress/gb_xapi_content/qurdatic','on clicking finish button');
