/**
 *  ==================================================
 *  SoftChalk LessonBuilder q_parameters.js
 *  Copyright 2003-2010 SoftChalk LLC
 *  All Rights Reserved.
 *
 *  http://www.softchalk.com
 *  ==================================================
 */

q_item=5;
group_item=1;
tableToggle_array=new Array();
f_done=new Array();
feed=new Array();
q_done=new Array();
scoreQ=new Array();
qOrder=new Array();
qOrder[0]=1;
qOrder[1]=2;
qOrder[2]=3;
qOrder[3]=4;
qOrder[4]=5;
num_pages=13;
//groupOrder1=1,2,3,4,5
//groupName1=WWII Overview
//groupOneAtATime1=false
//groupRandom1=false
//groupPoolSize1=5
//groupRetry1=false
//groupShow1=true
//groupScoreSummary1=false
//groupBorder1=true
scorm_completed_status=true;

//q_num=1;
inline_feedback1=true;
q_done[1]=false;
q_value1=1;
scoreQ[1]="yes";
mc_items1=4;
//ra_items1=1;
q_type1=1;
theQuestion1="World War II in Europe began on September 1, 1939, when</p><p>&nbsp;";
showCorrect1="no";
showHint1="no";
case_sensitive1="false";
partial_credit1=false;
feedbackRight1="Right! Good job!";
feedbackWrong1="Sorry, incorrect answer.";
feedbackPartial1="Partially correct.";
hint1="";
right_answers1=new Array(1);
right_answers1[0]="d";
answer_choices1=new Array(4);
answer_choices1[0]="Great Britain and France declared war on Germany and Austria over the seizure of Czech&#173;oslovakia.";
answer_choices1[1]="Russia invaded Poland.";
answer_choices1[2]="Italy attacked Crete.";
answer_choices1[3]="Germany invaded Poland.&nbsp;";
tableToggle_array[1]=true;
f_done[1]=false;
feed[1]=false;
//colorChoice1="_custom";
//tableClass1="expand";
//openerImage1="none.gif";
//allowRetry1=true;
//groupID1=1;

//q_num=2;
inline_feedback2=true;
q_done[2]=false;
q_value2=1;
scoreQ[2]="yes";
mc_items2=4;
//ra_items2=1;
q_type2=1;
theQuestion2="The first ground offensive action taken by the United States in world War II was";
showCorrect2="no";
showHint2="no";
case_sensitive2="false";
partial_credit2=false;
feedbackRight2="Right! Good job!";
feedbackWrong2="Sorry, incorrect answer.";
feedbackPartial2="Partially correct.";
hint2="";
right_answers2=new Array(1);
right_answers2[0]="a";
answer_choices2=new Array(4);
answer_choices2[0]="the Marine landing on Guadalcanal";
answer_choices2[1]="the invasion of Normandy in France";
answer_choices2[2]="the landing of American troops in Iceland";
answer_choices2[3]="the American landing on the island of Sicily";
tableToggle_array[2]=true;
f_done[2]=false;
feed[2]=false;
//colorChoice2="_custom";
//tableClass2="expand";
//openerImage2="none.gif";
//allowRetry2=true;
//groupID2=1;

//q_num=3;
inline_feedback3=true;
q_done[3]=false;
q_value3=1;
scoreQ[3]="yes";
mc_items3=4;
//ra_items3=1;
q_type3=3;
theQuestion3="Causes of World War 2 include";
showCorrect3="no";
showHint3="no";
case_sensitive3="false";
partial_credit3=false;
feedbackRight3="Right! Good job!";
feedbackWrong3="Sorry, incorrect answer.";
feedbackPartial3="Partially correct.";
hint3="";
right_answers3=new Array(1);
right_answers3[0]="a,d";
answer_choices3=new Array(4);
answer_choices3[0]="the German invasion of Poland";
answer_choices3[1]="the Italian invasion of Ethiopia";
answer_choices3[2]="the Spanish Civil War";
answer_choices3[3]="Japanese aggression in Asia";
tableToggle_array[3]=true;
f_done[3]=false;
feed[3]=false;
//colorChoice3="_custom";
//tableClass3="expand";
//openerImage3="none.gif";
//allowRetry3=true;
//groupID3=1;

//q_num=4;
inline_feedback4=true;
q_done[4]=false;
q_value4=1;
scoreQ[4]="yes";
mc_items4=4;
//ra_items4=1;
q_type4=3;
theQuestion4="Major turning points in World War II include";
showCorrect4="no";
showHint4="no";
case_sensitive4="false";
partial_credit4=false;
feedbackRight4="Right! Good job!";
feedbackWrong4="Sorry, incorrect answer.";
feedbackPartial4="Partially correct.";
hint4="";
right_answers4=new Array(1);
right_answers4[0]="b,c";
answer_choices4=new Array(4);
answer_choices4[0]="the German invasion of Great Britain";
answer_choices4[1]="the German defeat at Stalingrad";
answer_choices4[2]="the Battle of Midway";
answer_choices4[3]="the Japanese capture of Attu and Kiska";
tableToggle_array[4]=true;
f_done[4]=false;
feed[4]=false;
//colorChoice4="_custom";
//tableClass4="expand";
//openerImage4="none.gif";
//allowRetry4=true;
//groupID4=1;

//q_num=5;
inline_feedback5=true;
q_done[5]=false;
q_value5=1;
scoreQ[5]="yes";
mc_items5=4;
//ra_items5=1;
q_type5=1;
theQuestion5="Immediately after Pearl Harbor American and British strategists decided to";
showCorrect5="no";
showHint5="no";
case_sensitive5="false";
partial_credit5=false;
feedbackRight5="Right! Good job!";
feedbackWrong5="Sorry, incorrect answer.";
feedbackPartial5="Partially correct.";
hint5="";
right_answers5=new Array(1);
right_answers5[0]="c";
answer_choices5=new Array(4);
answer_choices5[0]="concentrate first against Japan.";
answer_choices5[1]="develop the atomic bomb.";
answer_choices5[2]="concentrate first against Germany.";
answer_choices5[3]="develop radar.</p><p>&nbsp;";
tableToggle_array[5]=true;
f_done[5]=false;
feed[5]=false;
//colorChoice5="_custom";
//tableClass5="expand";
//openerImage5="none.gif";
//allowRetry5=true;
//groupID5=1;

